const event = Object.freeze({
  NEW_ORDER: 'NEW_ORDER',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  FUND_WALLET: 'FUND_WALLET',
  GENERATE_ACCOUNT_VIRTUAL: 'GENERATE_ACCOUNT_VIRTUAL',
  ORDER_PAYMENT: 'ORDER_PAYMENT',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REJECTED: 'ORDER_REJECTED',

  // Special Withdrawal Events
  SW_NEW_REQUEST: 'SW_NEW_REQUEST',
  SW_REQUEST_ACCEPTED: 'SW_REQUEST_ACCEPTED',
  SW_REQUEST_REJECTED: 'SW_REQUEST_REJECTED',
  SW_REQUEST_CANCELLED: 'SW_REQUEST_CANCELLED',
  SW_QR_SCANNED: 'SW_QR_SCANNED',
  SW_REQUEST_COMPLETED: 'SW_REQUEST_COMPLETED',
});

export default event;
