const event = Object.freeze({
  NEW_ORDER: 'NEW_ORDER',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  FUND_WALLET: 'FUND_WALLET',
  GENERATE_ACCOUNT_VIRTUAL: 'GENERATE_ACCOUNT_VIRTUAL',
});

export default event;
